language: ruby
rvm:
  - 2.0.0
sudo: false
branches:
  only:
  - master
before_install:
  - set -e
  - openssl aes-256-cbc -K $encrypted_72e767f5966c_key -iv $encrypted_72e767f5966c_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.email "travis@seedramp.com"
  - git config --global user.name "travis"
install:
  - travis_retry bundle install
  - travis_retry npm install html-minifier@1.3.0 -g
script:
  - make
  - git clone git@github.com:yegor256/seedramp.git tmp
  - cd tmp
  - git checkout gh-pages
  - rm -rf *
  - mv ../target/* .
  - git add .
  - git commit -am 'deploy' --allow-empty
  - git push origin gh-pages
  - cd ..
  - rm -rf tmp
